
logger:
  json: true
  stdout: true
  file:
    name: 'logs/agent.log'
    max_size: 50
    max_backup: 100
    max_age: 31
    compressed: true
  level: 'debug'

server:
  http:
    timeout: 6
    hmac_header: ''
    hmac_secret: 'ab2316584873095f017f6dfa7a9415794f563fcc473eb3fe65b9167e37fd5a4b'
    bearer_token: 'ab2316584873095f017f6dfa7a9415794f563fcc473eb3fe65b9167e37fd5a4b'
    jwt:
      secret: 'ab2316584873095f017f6dfa7a9415794f563fcc473eb3fe65b9167e37fd5a4b'
      access_token_exp: 1
      refresh_token: true
      refresh_token_exp: 10
    allowed_origins: '*'
    allowed_headers: 'X-Requested-With,Content-Type,Authorization'
    allowed_methods: 'GET,POST,PUT,DELETE,HEAD'

  repo:
    # driver: 'map'
    driver: 'pgx'
    conn_str: 'host=testpghost user=test password=test123 dbname=woong_auth port=5432 sslmode=disable TimeZone=Asia/Seoul'
    # used when driver is oci8, postgres, mssql...
    max_idle_conns: 5
    max_open_conns: 25
    conn_max_lifetime_in_min: 15

client:
  oauth2:
    # google, woong, apple, kakao, naver
    token:
      source: 'google'
      id_key_name: 'tid'
      id_token_key_name: 'id_token'
      token_source_key_name: 'token_source'
    client_id: ''
    client_secret: ''
    redirect_url: 'https://localhost:5558/v1/auth/callback/{token_source}'
    scopes:
      - 'openid'
      - 'https://www.googleapis.com/auth/userinfo.email'
      - 'https://www.googleapis.com/auth/userinfo.profile'
    auth_url: 'https://accounts.google.com/o/oauth2/auth'
    token_url: 'https://oauth2.googleapis.com/token'
    openid_conf_url: 'https://accounts.google.com/.well-known/openid-configuration'

    authrequest:
      # direct address
      response_url: 'https://localhost:5558/v1/auth/request/{token_source}/{auth_request_id}'
      auth_url: 'https://localhost:5558/v1/auth/authorize/{token_source}/{auth_request_id}'
      wait: 300
    # cookie:
    #   expires_in: 60
    #   token_identifier_name: 'tid'
    #   id_token_name: 'id_token'
    #   state_name: 'state'
    #   code_verifier_name: 'code_verifier'

  # user_http:
  #   url: 'https://192.168.0.92:8080'
  #   bearer_token: 'ab2316584873095f017f6dfa7a9415794f563fcc473eb3fe65b9167e37fd5a4b'

  # user_grpc:
  #   addr: '192.168.0.92:42001,192.168.0.92:42001'
  #   keep_alive:
  #     time: 60
  #     timeout: 1
  #     permit_without_stream: true
  #   resolver_scheme: 'user'
  #   resolver_service_name: 'user-service'
  #   default_service_config: >
  #     {"loadBalancingConfig": [{"round_robin":{}}],
  #       "methodConfig": [{
  #         "name": [{}],
  #         "waitForReady": true,
  #         "retryPolicy": {
  #           "MaxAttempts": 3,
  #           "InitialBackoff": ".01s",
  #           "MaxBackoff": ".01s",
  #           "BackoffMultiplier": 1.0,
  #           "RetryableStatusCodes": [ "UNAVAILABLE" ]
  #         }
  #       }]
  #     }
  #   ca_cert_pem: './certs/server.crt'
  #   cert_server_name: 'localhost'
  #   dial_block: false